services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: log-db

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yogesh#1409

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: intelligent-log-analyzer

    depends_on:
      - postgres

    ports:
      - "7070:7070"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Yogesh#1409

volumes:
  postgres-data: